
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action dialogWarningAction;
	private global::Gtk.Action editAction;
	private global::Gtk.Action replyAllAction;
	private global::Gtk.ToggleAction dbgAction;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.Entry queryEntry;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeviewSearch;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView treeviewList;
	private global::Gtk.Table table1;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.Label label9;
	private global::Gtk.Label labelCc;
	private global::Gtk.Label labelDate;
	private global::Gtk.Label labelFrom;
	private global::Gtk.Label labelSubject;
	private global::Gtk.Label labelTags;
	private global::Gtk.Label labelTags1;
	private global::Gtk.Label labelTo;
	private global::Gtk.ScrolledWindow scrolledwindowWeb;
	private global::NotMuchGUI.TagsWidget tagsWidget;
	private global::Gtk.Statusbar statusbar2;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.dialogWarningAction = new global::Gtk.Action ("dialogWarningAction", global::Mono.Unix.Catalog.GetString ("GC"), "", "gtk-dialog-warning");
		this.dialogWarningAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("GC");
		w1.Add (this.dialogWarningAction, null);
		this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Reply"), null, "gtk-edit");
		this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Reply");
		w1.Add (this.editAction, null);
		this.replyAllAction = new global::Gtk.Action ("replyAllAction", global::Mono.Unix.Catalog.GetString ("Reply All"), null, "gtk-edit");
		this.replyAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Reply All");
		w1.Add (this.replyAllAction, null);
		this.dbgAction = new global::Gtk.ToggleAction ("dbgAction", global::Mono.Unix.Catalog.GetString ("Dbg"), null, null);
		this.dbgAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dbg");
		w1.Add (this.dbgAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.AllowShrink = true;
		this.DefaultWidth = 1300;
		this.DefaultHeight = 800;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='dialogWarningAction' action='dialogWarningAction'/><toolitem name='editAction' action='editAction'/><toolitem name='replyAllAction' action='replyAllAction'/><toolitem name='dbgAction' action='dbgAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(1));
		this.vbox2.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.queryEntry = new global::Gtk.Entry ();
		this.queryEntry.CanFocus = true;
		this.queryEntry.Name = "queryEntry";
		this.queryEntry.IsEditable = true;
		this.queryEntry.InvisibleChar = '•';
		this.vbox2.Add (this.queryEntry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.queryEntry]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 184;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeviewSearch = new global::Gtk.TreeView ();
		this.treeviewSearch.CanFocus = true;
		this.treeviewSearch.Name = "treeviewSearch";
		this.GtkScrolledWindow.Add (this.treeviewSearch);
		this.hpaned1.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeviewList = new global::Gtk.TreeView ();
		this.treeviewList.CanFocus = true;
		this.treeviewList.Name = "treeviewList";
		this.treeviewList.FixedHeightMode = true;
		this.treeviewList.Reorderable = true;
		this.GtkScrolledWindow1.Add (this.treeviewList);
		this.hpaned1.Add (this.GtkScrolledWindow1);
		this.vbox2.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hpaned1]));
		w8.Position = 2;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(10));
		this.table1.BorderWidth = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 1F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("From");
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 1F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Subject");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 1F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("To");
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.Xalign = 1F;
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Cc");
		this.table1.Add (this.label9);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelCc = new global::Gtk.Label ();
		this.labelCc.Name = "labelCc";
		this.labelCc.Xalign = 0F;
		this.labelCc.LabelProp = global::Mono.Unix.Catalog.GetString ("label10");
		this.labelCc.Selectable = true;
		this.table1.Add (this.labelCc);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelCc]));
		w13.TopAttach = ((uint)(3));
		w13.BottomAttach = ((uint)(4));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelDate = new global::Gtk.Label ();
		this.labelDate.Name = "labelDate";
		this.labelDate.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
		this.table1.Add (this.labelDate);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelDate]));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelFrom = new global::Gtk.Label ();
		this.labelFrom.Name = "labelFrom";
		this.labelFrom.Xalign = 0F;
		this.labelFrom.LabelProp = global::Mono.Unix.Catalog.GetString ("labelFrom");
		this.labelFrom.Selectable = true;
		this.table1.Add (this.labelFrom);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFrom]));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelSubject = new global::Gtk.Label ();
		this.labelSubject.Name = "labelSubject";
		this.labelSubject.Xalign = 0F;
		this.labelSubject.LabelProp = global::Mono.Unix.Catalog.GetString ("labelSubject");
		this.labelSubject.Selectable = true;
		this.table1.Add (this.labelSubject);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelSubject]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelTags = new global::Gtk.Label ();
		this.labelTags.Name = "labelTags";
		this.labelTags.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
		this.table1.Add (this.labelTags);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTags]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelTags1 = new global::Gtk.Label ();
		this.labelTags1.Name = "labelTags1";
		this.labelTags1.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
		this.table1.Add (this.labelTags1);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTags1]));
		w18.TopAttach = ((uint)(2));
		w18.BottomAttach = ((uint)(3));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelTo = new global::Gtk.Label ();
		this.labelTo.Name = "labelTo";
		this.labelTo.Xalign = 0F;
		this.labelTo.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
		this.labelTo.Selectable = true;
		this.table1.Add (this.labelTo);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTo]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindowWeb = new global::Gtk.ScrolledWindow ();
		this.scrolledwindowWeb.CanFocus = true;
		this.scrolledwindowWeb.Name = "scrolledwindowWeb";
		this.scrolledwindowWeb.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.scrolledwindowWeb.ShadowType = ((global::Gtk.ShadowType)(1));
		this.vbox2.Add (this.scrolledwindowWeb);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scrolledwindowWeb]));
		w21.Position = 4;
		// Container child vbox2.Gtk.Box+BoxChild
		this.tagsWidget = new global::NotMuchGUI.TagsWidget ();
		this.tagsWidget.Events = ((global::Gdk.EventMask)(256));
		this.tagsWidget.Name = "tagsWidget";
		this.vbox2.Add (this.tagsWidget);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tagsWidget]));
		w22.Position = 5;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar2 = new global::Gtk.Statusbar ();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 6;
		// Container child statusbar2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.statusbar2.Add (this.label1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.statusbar2 [this.label1]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child statusbar2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.statusbar2.Add (this.label2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.statusbar2 [this.label2]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child statusbar2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.statusbar2.Add (this.label3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.statusbar2 [this.label3]));
		w25.PackType = ((global::Gtk.PackType)(1));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox2.Add (this.statusbar2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar2]));
		w26.PackType = ((global::Gtk.PackType)(1));
		w26.Position = 6;
		w26.Expand = false;
		w26.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dialogWarningAction.Activated += new global::System.EventHandler (this.OnGcActionActivated);
		this.editAction.Activated += new global::System.EventHandler (this.OnReplyActionActivated);
		this.replyAllAction.Activated += new global::System.EventHandler (this.OnReplyAllActionActivated);
		this.dbgAction.Activated += new global::System.EventHandler (this.OnDbgActionActivated);
		this.queryEntry.Changed += new global::System.EventHandler (this.OnQueryEntryChanged);
		this.queryEntry.Activated += new global::System.EventHandler (this.OnQueryEntryActivated);
		this.treeviewSearch.CursorChanged += new global::System.EventHandler (this.OnTreeviewSearchCursorChanged);
		this.treeviewList.CursorChanged += new global::System.EventHandler (this.OnTreeviewListCursorChanged);
	}
}
