
// This file has been generated by the GUI designer. Do not modify.
namespace NotMuchGUI
{
	public partial class RunWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.ScrolledWindow termScrolledwindow;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NotMuchGUI.RunWindow
			this.Name = "NotMuchGUI.RunWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("RunWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NotMuchGUI.RunWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.termScrolledwindow = new global::Gtk.ScrolledWindow ();
			this.termScrolledwindow.CanFocus = true;
			this.termScrolledwindow.Name = "termScrolledwindow";
			this.termScrolledwindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox1.Add (this.termScrolledwindow);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.termScrolledwindow]));
			w1.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 691;
			this.DefaultHeight = 334;
			this.Show ();
		}
	}
}
