
// This file has been generated by the GUI designer. Do not modify.
namespace NotMuchGUI
{
	public partial class ComposeWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button editButton;
		private global::Gtk.Button sendButton;
		private global::Gtk.Button button8;
		private global::NotMuchGUI.MessageWidget messagewidget1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NotMuchGUI.ComposeWindow
			this.Name = "NotMuchGUI.ComposeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ComposeWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NotMuchGUI.ComposeWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.editButton = new global::Gtk.Button ();
			this.editButton.CanFocus = true;
			this.editButton.Name = "editButton";
			this.editButton.UseUnderline = true;
			this.editButton.Label = global::Mono.Unix.Catalog.GetString ("Edit");
			this.hbuttonbox2.Add (this.editButton);
			global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.editButton]));
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.sendButton = new global::Gtk.Button ();
			this.sendButton.CanFocus = true;
			this.sendButton.Name = "sendButton";
			this.sendButton.UseUnderline = true;
			this.sendButton.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.hbuttonbox2.Add (this.sendButton);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.sendButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbuttonbox2.Add (this.button8);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button8]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.messagewidget1 = new global::NotMuchGUI.MessageWidget ();
			this.messagewidget1.Events = ((global::Gdk.EventMask)(256));
			this.messagewidget1.Name = "messagewidget1";
			this.messagewidget1.ShowHtmlSource = false;
			this.vbox2.Add (this.messagewidget1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.messagewidget1]));
			w5.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 715;
			this.DefaultHeight = 455;
			this.Show ();
			this.editButton.Clicked += new global::System.EventHandler (this.OnEditButtonClicked);
		}
	}
}
