
// This file has been generated by the GUI designer. Do not modify.
namespace NotMuchGUI
{
	public partial class TagsWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView tagsTreeview;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button newButton;
		private global::Gtk.Button resetButton;
		private global::Gtk.Button applyButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NotMuchGUI.TagsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NotMuchGUI.TagsWidget";
			// Container child NotMuchGUI.TagsWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tagsTreeview = new global::Gtk.TreeView ();
			this.tagsTreeview.CanFocus = true;
			this.tagsTreeview.Name = "tagsTreeview";
			this.GtkScrolledWindow.Add (this.tagsTreeview);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.newButton = new global::Gtk.Button ();
			this.newButton.CanFocus = true;
			this.newButton.Name = "newButton";
			this.newButton.UseUnderline = true;
			this.newButton.Label = global::Mono.Unix.Catalog.GetString ("New");
			this.hbox1.Add (this.newButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.newButton]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.resetButton = new global::Gtk.Button ();
			this.resetButton.CanFocus = true;
			this.resetButton.Name = "resetButton";
			this.resetButton.UseUnderline = true;
			this.resetButton.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.hbox1.Add (this.resetButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.resetButton]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.applyButton = new global::Gtk.Button ();
			this.applyButton.CanFocus = true;
			this.applyButton.Name = "applyButton";
			this.applyButton.UseUnderline = true;
			this.applyButton.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.hbox1.Add (this.applyButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.applyButton]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.applyButton.Clicked += new global::System.EventHandler (this.OnApplyButtonClicked);
			this.resetButton.Clicked += new global::System.EventHandler (this.OnResetButtonClicked);
			this.newButton.Clicked += new global::System.EventHandler (this.OnNewButtonClicked);
		}
	}
}
