
// This file has been generated by the GUI designer. Do not modify.
namespace NotMuchGUI
{
	public partial class MessageListWidget
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView messagesTreeview;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NotMuchGUI.MessageListWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NotMuchGUI.MessageListWidget";
			// Container child NotMuchGUI.MessageListWidget.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.messagesTreeview = new global::Gtk.TreeView ();
			this.messagesTreeview.CanFocus = true;
			this.messagesTreeview.Name = "messagesTreeview";
			this.messagesTreeview.FixedHeightMode = true;
			this.messagesTreeview.Reorderable = true;
			this.GtkScrolledWindow.Add (this.messagesTreeview);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
